version: '2'
services:
  aqua-csp-service:
    image: edvancecn/aquacsp:2.6.3
    hostname: aqua-csp
    environment:
      BATCH_INSTALL_ENFORCE_MODE: n
      BATCH_INSTALL_GATEWAY: csp
      BATCH_INSTALL_NAME: default
      BATCH_INSTALL_TOKEN: aqua-csp
      SCALOCK_GATEWAY_NAME: csp
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp/aqua-data:/var/lib/postgresql/data
    ports:
    - 9090:8080/tcp
    - 8443:8443/tcp
    - 3622:3622/tcp
    user: root